engines:
  eslint:
    enabled: true
    channel: "eslint-2"
    exclude_fingerprints:
    - 27bf3248f5eefa5baf8241a39dc79729
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- "public/javascripts/bootstrap-timepicker.js"
- "public/javascripts/bootstrap-timepicker.min.js"
- "public/javascripts/bootstrap-datepicker.js"
- "public/javascripts/bootstrap.min.js"
- "public/javascripts/fullcalendar.min.js"
- "public/javascripts/jquery.min.js"
- "public/javascripts/moment.min.js"
